# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "st-elsewhere"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Doll"]
  s.date = "2013-09-11"
  s.description = "This gem provides has_many_elsewhere, an ActiveRecord class method to support many to many relationships in Rails applications, across multiple database connections."
  s.email = "brian@emphaticsolutions.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "changelog.rdoc",
    "lib/st-elsewhere.rb",
    "st-elsewhere.gemspec",
    "tasks/st-elsewhere_tasks.rake",
    "test/st-elsewhere_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/briandoll/st-elsewhere"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.5"
  s.summary = "St. Elsewhere supports has_many :through relationships across different databases"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

